Controllers/HubController.cs
using Microsoft.AspNetCore.Mvc;
using Test2.Data;
using Test2.Interfaces;
using Test2.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Test2.Controllers
{
    public class HubController : Controller
    {

        private readonly IHubService _hubService;

        public HubController(IHubService hubService)
        {
            _hubService = hubService;
        }
        public async Task<IActionResult> Index()
        {
            var userTeams = await _hubService.GetAllUserTeams();
            var userLeagues = await _hubService.GetAllUserLeagues();
            var userPlayers = await _hubService.GetAllUserPlayers();
            var userFixtures = await _hubService.GetAllUserFixtureAndResults();


            // var userLeagues = await _hubService.GetAllUserLeagues();
            var hubViewModel = new HubViewModel()
            {
                Teams = userTeams,
                Leagues = userLeagues,
                Players = userPlayers,
                Fixtures = userFixtures


                // Leagues = userLeagues
            };
            return View(hubViewModel);
        }
    }
}

Controllers/LeagueController.cs
using Microsoft.AspNetCore.Mvc;
using Test2.Data;
using Test2.Interfaces;
using Test2.Models;
using Test2.Service;
using Test2.ViewModels;

namespace Test2.Controllers
{
    public class LeagueController : Controller
    {
       // private readonly ApplicationDbContext _context;
        private readonly ILeagueService _leagueService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public LeagueController( ILeagueService leagueService, IHttpContextAccessor httpContextAccessor)
        {
            _leagueService = leagueService;
            _httpContextAccessor = httpContextAccessor;
           // _context = context;

        }


        public async Task<IActionResult> Index()
        {
            //List<League> leagues = _context.Leagues.ToList();
            //return View(leagues);
            IEnumerable<League> leagues = await _leagueService.GetAll();
            return View(leagues);
        }

        public async Task<IActionResult> Detail(int id)
        {
            League league = await _leagueService.GetByIdAsync(id);
            return View(league);
        }

        public async Task<IActionResult> Leaguetable()
        {
           
            return View();
        }

        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createLeagueViewModel = new CreateLeagueViewModel { BasketballNiId = curUserId };

            return View(createLeagueViewModel);
        }

        [HttpPost]

        public async Task<IActionResult> Create(League league)
        {
            if (!ModelState.IsValid)
            {
                
                return View(league);
            }
            _leagueService.Add(league);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var league = await _leagueService.GetByIdAsync(id);
            if (league == null) return View("Error");
            var leagueVM = new EditLeagueViewModel
            {
                Leaguename = league.Leaguename,
                LeagueDescription = league.LeagueDescription,
                Level = league.Level


            };
            return View(leagueVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditLeagueViewModel leagueVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit team information");
                return View(leagueVM);
            }

            //var userLeague = await _leagueService.GetByIdAsyncNoTracking(id); 
            

            var league = new League
            {
                League_id = id,
                Leaguename = leagueVM.Leaguename,
                LeagueDescription = leagueVM.LeagueDescription,
                Level = leagueVM.Level,
                
            };

            _leagueService.Update(league);

            return RedirectToAction("Index");

        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var leagueDetails = await _leagueService.GetByIdAsync(id);
            if (leagueDetails == null) return View("Error");
            return View(leagueDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteLeague(int id)
        {
            var leagueDetails = await _leagueService.GetByIdAsync(id);
            if (leagueDetails == null) return View("Error");

            _leagueService.Delete(leagueDetails);
            return RedirectToAction("Index");
        }


    }
}

Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using Test2.Data;
using Test2.Models;
using Test2.Interfaces;
using Test2.Service;
using Test2.ViewModels;


namespace Test2.Controllers
{
    public class PlayerController : Controller
    {
        
        private readonly IPlayerService _playerService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        // private readonly ApplicationDbContext _context;

        public PlayerController( IPlayerService playerService, IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            _playerService= playerService;
            //_context = context;
        }


        public async Task<IActionResult> Index()
        {
            //IEnumerable<Player> players = await _playerService.GetAll();
            //return View(players);

            IEnumerable<Player> players = await _playerService.GetAll();
            return View(players);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Player player = await _playerService.GetByIdAsync(id);
            return View(player);
        }

        //public IActionResult Create()
        //{
        //    var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
        //    var createPlayerViewModel = new CreatePlayerViewModel { BasketballNiId = curUserId };

        //    return View(createPlayerViewModel);
        //}

        //public async Task<IActionResult> Create(Player player)
        //{
        //    if (!ModelState.IsValid)
        //    {

        //        return View(player);
        //    }
        //    _playerService.Add(player);
        //    return RedirectToAction("Index");

        //}

        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createPlayerViewModel = new CreatePlayerViewModel { BasketballNiId = curUserId };

            return View(createPlayerViewModel);
        }

        [HttpPost]

        public async Task<IActionResult> Create(Player player)
        {
            if (!ModelState.IsValid)
            {
                return View(player);
            }
            _playerService.Add(player);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var player = await _playerService.GetByIdAsync(id);
            if (player == null) return View("Error");
            var playerVM = new EditPlayerViewModel
            {
                Name = player.Name,
                TeamName = player.TeamName,
                Points = player.Points,
                Rebounds = player.Rebounds,
                Assists = player.Assists,
                Steals = player.Steals,
                Blocks = player.Blocks
            };

            return View(playerVM);
        }
        

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditPlayerViewModel playerVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit team information");
                return View("Edit", playerVM);
            }

            var userPlayer = await _playerService.GetByIdAsyncNoTracking(id);

            var player = new Player 
            {
                Player_id = id,
                Name = playerVM.Name,
                TeamName =playerVM.TeamName,
                Points = playerVM.Points,
                Rebounds = playerVM.Rebounds,
                Assists = playerVM.Assists,
                Steals = playerVM.Steals,
                Blocks = playerVM.Blocks
            };

            _playerService.Update(player);

            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Delete(int id)
        {
            var playerDetails = await _playerService.GetByIdAsync(id);
            if (playerDetails == null) return View("Error");
            return View(playerDetails);
        }



        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePlayer(int id)
        {
            var playerDetails =  await _playerService.GetByIdAsync(id);
            //var playerDetails = _context.Players.FirstOrDefault(o => o.Player_id == id);
            if (playerDetails == null) return View("Error");

            _playerService.Delete(playerDetails);
            return RedirectToAction("Index");
        }



    }
}

Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Test2.Data;
using Test2.Interfaces;
using Test2.Models;
using Test2.ViewModels;
//using Test2.Helpers;

namespace Test2.Controllers
{
    public class TeamController : Controller
    {

        private readonly ITeamService _teamService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public TeamController(ITeamService teamService, IHttpContextAccessor httpContextAccessor)
        {
            _teamService = teamService;
            _httpContextAccessor = httpContextAccessor;


        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Team> teams = await _teamService.GetAll();
            return View(teams);

            //List<Team> teams = _context.Teams.ToList();
            //return View(teams);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Team team = await _teamService.GetByIdAsync(id);
            return View(team);
        }


        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createTeamViewModel = new CreateTeamViewModel { BasketballNiId = curUserId };
               
            return View(createTeamViewModel);
        }


        

    [HttpPost]
    public async Task<IActionResult> Create(Team team)
    {
        if (!ModelState.IsValid)
        {

            return View(team);
        }
        _teamService.Add(team);
        return RedirectToAction("Index");

    }

    public async Task<IActionResult> Edit(int id)
        {
            var team = await _teamService.GetByIdAsync(id);
            if (team == null) return View("Error");
            var teamVM = new EditTeamViewModel
            {
                Name = team.Name,
                Description = team.Description,
                LeagueName = team.LeagueName
            };
            return View(teamVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditTeamViewModel teamVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit team information");
                return View("Edit", teamVM);
            }

            var userTeam = await _teamService.GetByIdAsyncNoTracking(id);

            var team = new Team
            {
                Id = id,
                Name = teamVM.Name,
                Description = teamVM.Description,
                LeagueName = teamVM.LeagueName,
            };

            _teamService.Update(team);

            return RedirectToAction("Index");

        }


        public async Task<IActionResult> Delete (int id)
        {
            var teamDetails = await _teamService.GetByIdAsync(id);
            if (teamDetails == null) return View("Error");
            return View(teamDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteTeam(int id)
        {
            var teamDetails = await _teamService.GetByIdAsync(id);
            if (teamDetails == null) return View("Error");

            _teamService.Delete(teamDetails);
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_Breadcrumbs.cshtml
@if (ViewContext.RouteData.Values["controller"].ToString().ToLower() != "home")
{
    <section class="section-box mb-4">
        <div class="align-content-lg-start nav-breadcrums">
            <div class="container">
                <div class="breadcrumb">
                    <ul>
                        <li class="home">@Html.ActionLink("Home", "Index", "Home") </li>
                        <li>@Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index")</li>
@*                        <li>@Html.ActionLink(ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["action"].ToString()) </li>
*@                    </ul>
                </div>
            </div>
        </div>
    </section>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Basketball NI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Test2.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
            <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-light bg-success border-bottom box-shadow">
            <div class="container-fluid">
            <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Test2</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="League" asp-action="Index">League</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Team" asp-action="Index">Team</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="FixtureAndResult" asp-action="Index">Fixtures and Results</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Player" asp-action="Index">Player</a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Hub" asp-action="Index">Hub</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        @if (User.Identity.IsAuthenticated && User.IsInRole("coach"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Hub" asp-action="Index">Hub</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>

                        }

                    </ul>
                    <img width="200" src="https://th.bing.com/th/id/R.f8ba61c51225d206c63cb7312dc5e4b4?rik=hwATBiueb8kReg&riu=http%3a%2f%2fwww.basketballni.com%2fwp-content%2fuploads%2f2015%2f09%2fBNI-Logo.png&ehk=ALyuN15Wg8cR8eH1b%2fwCHA6N7ugyaUcYtrrBLuMDH7E%3d&risl=&pid=ImgRaw&r=0" />
                </div>
            </div>
        </nav>
    </header>
    <partial name="_Breadcrumbs" />
    <div class="container">

        <main role="main" class="main">
            @*// <partial name="_Notification" />*@
           
            @RenderBody()
        </main>

@*        <main role="main" class="pb-3">
            @RenderBody()
        </main>*@
    </div>





    <footer class="footer mt-50 bg-success">
        <div class="container">
            <div class="text-light btn-outline-warning">
                &copy; 2022 - Basketball NI - <a class="text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>