ViewModels/HubViewModel.cs
using Test2.Models;

namespace Test2.ViewModels
{
    public class HubViewModel
    {
        public List<Team> Teams { get; set; }
        
        public List<League> Leagues { get; set; }
    
        public List<Player> Players { get; set; }

        public List<FixtureAndResult> Fixtures { get; set; }
    }
}

Controllers/FixtureAndResultController.cs
using Microsoft.AspNetCore.Mvc;
using Test2.Data;
using Test2.Interfaces;
using Test2.Models;
using Test2.Service;
using Test2.ViewModels;

namespace Test2.Controllers
{
    public class FixtureAndResultController : Controller
    {
        private readonly IFixtureAndResultService _fixtureAndResultService;
        private readonly IHttpContextAccessor _httpContextAccessor;


        public FixtureAndResultController(IFixtureAndResultService fixtureAndResultService, IHttpContextAccessor httpContextAccessor)
        {
            _fixtureAndResultService = fixtureAndResultService;
            _httpContextAccessor = httpContextAccessor;
        }


        public async Task<IActionResult> Index()
        {
            //List<FixtureAndResult> fixtureAndResults = _context.FixturesAndResults.ToList();
            //return View(fixtureAndResults);

            IEnumerable<FixtureAndResult> fixtureAndResults = await _fixtureAndResultService.GetAll();
            return View(fixtureAndResults);
        }

        public async Task<IActionResult> Detail(int id)
        {
            FixtureAndResult fixtureAndResult = await _fixtureAndResultService.GetByIdAsync(id);
            return View(fixtureAndResult);
        }

        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createFixtureAndResultViewModel = new CreateFixtureAndResultViewModel { BasketballNiId = curUserId};
            return View(createFixtureAndResultViewModel);
        }

        [HttpPost]

        public async Task<IActionResult> Create(FixtureAndResult fixtureAndResult)
        {
            if (!ModelState.IsValid)
            {
                return View(fixtureAndResult);
            }
            _fixtureAndResultService.Add(fixtureAndResult);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var far = await _fixtureAndResultService.GetByIdAsync(id);
            if (far == null) return View("Error");
            var farVM = new EditFixtureAndResultViewModel
            {
                Hometeam = far.Hometeam,
                Awayteam = far.Awayteam,
                Homescore = far.Homescore,
                Awayscore = far.Awayscore,
                DatefGame = far.DatefGame

            };

            return View(farVM);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditFixtureAndResultViewModel farVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit team information");
                return View("Edit", farVM);
            }

            var userFar = await _fixtureAndResultService.GetByIdAsyncNoTracking(id);

            var far = new FixtureAndResult
            {
                Match_id = id,
                Hometeam = farVM.Hometeam,
                Homescore = farVM.Homescore,
                Awayteam = farVM.Awayteam,
                Awayscore = farVM.Awayscore,
                DatefGame = farVM.DatefGame
            };

            _fixtureAndResultService.Update(far);

            return RedirectToAction("Index");


        }

        public async Task<IActionResult> Delete(int id)
        {
            var farDetails = await _fixtureAndResultService.GetByIdAsync(id);
            if (farDetails == null) return View("Error");
            return View(farDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteFixtureAndResult(int id)
        {
            var farDetails = await _fixtureAndResultService.GetByIdAsync(id);
            if (farDetails == null) return View("Error");

            _fixtureAndResultService.Delete(farDetails);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HubController.cs
using Microsoft.AspNetCore.Mvc;
using Test2.Data;
using Test2.Interfaces;
using Test2.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Test2.Controllers
{
    public class HubController : Controller
    {

        private readonly IHubService _hubService;

        public HubController(IHubService hubService)
        {
            _hubService = hubService;
        }
        public async Task<IActionResult> Index()
        {
            var userTeams = await _hubService.GetAllUserTeams();
            var userLeagues = await _hubService.GetAllUserLeagues();
            var userPlayers = await _hubService.GetAllUserPlayers();
            var userFixtures = await _hubService.GetAllUserFixtureAndResults();


            // var userLeagues = await _hubService.GetAllUserLeagues();
            var hubViewModel = new HubViewModel()
            {
                Teams = userTeams,
                Leagues = userLeagues,
                Players = userPlayers,
                Fixtures = userFixtures


                // Leagues = userLeagues
            };
            return View(hubViewModel);
        }
    }
}

Controllers/LeagueController.cs
using Microsoft.AspNetCore.Mvc;
using Test2.Data;
using Test2.Interfaces;
using Test2.Models;
using Test2.Service;
using Test2.ViewModels;

namespace Test2.Controllers
{
    public class LeagueController : Controller
    {
       // private readonly ApplicationDbContext _context;
        private readonly ILeagueService _leagueService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public LeagueController( ILeagueService leagueService, IHttpContextAccessor httpContextAccessor)
        {
            _leagueService = leagueService;
            _httpContextAccessor = httpContextAccessor;
           // _context = context;

        }


        public async Task<IActionResult> Index()
        {
            //List<League> leagues = _context.Leagues.ToList();
            //return View(leagues);
            IEnumerable<League> leagues = await _leagueService.GetAll();
            return View(leagues);
        }

        public async Task<IActionResult> Detail(int id)
        {
            League league = await _leagueService.GetByIdAsync(id);
            return View(league);
        }

        public async Task<IActionResult> Leaguetable()
        {
           
            return View();
        }

        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createLeagueViewModel = new CreateLeagueViewModel { BasketballNiId = curUserId };

            return View(createLeagueViewModel);
        }

        [HttpPost]

        public async Task<IActionResult> Create(League league)
        {
            if (!ModelState.IsValid)
            {
                
                return View(league);
            }
            _leagueService.Add(league);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var league = await _leagueService.GetByIdAsync(id);
            if (league == null) return View("Error");
            var leagueVM = new EditLeagueViewModel
            {
                Leaguename = league.Leaguename,
                LeagueDescription = league.LeagueDescription,
                Level = league.Level


            };
            return View(leagueVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditLeagueViewModel leagueVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit team information");
                return View(leagueVM);
            }

            //var userLeague = await _leagueService.GetByIdAsyncNoTracking(id); 
            

            var league = new League
            {
                League_id = id,
                Leaguename = leagueVM.Leaguename,
                LeagueDescription = leagueVM.LeagueDescription,
                Level = leagueVM.Level,
                
            };

            _leagueService.Update(league);

            return RedirectToAction("Index");

        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var leagueDetails = await _leagueService.GetByIdAsync(id);
            if (leagueDetails == null) return View("Error");
            return View(leagueDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteLeague(int id)
        {
            var leagueDetails = await _leagueService.GetByIdAsync(id);
            if (leagueDetails == null) return View("Error");

            _leagueService.Delete(leagueDetails);
            return RedirectToAction("Index");
        }


    }
}

Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using Test2.Data;
using Test2.Models;
using Test2.Interfaces;
using Test2.Service;
using Test2.ViewModels;


namespace Test2.Controllers
{
    public class PlayerController : Controller
    {
        
        private readonly IPlayerService _playerService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        // private readonly ApplicationDbContext _context;

        public PlayerController( IPlayerService playerService, IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            _playerService= playerService;
            //_context = context;
        }


        public async Task<IActionResult> Index()
        {
            //IEnumerable<Player> players = await _playerService.GetAll();
            //return View(players);

            IEnumerable<Player> players = await _playerService.GetAll();
            return View(players);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Player player = await _playerService.GetByIdAsync(id);
            return View(player);
        }

        //public IActionResult Create()
        //{
        //    var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
        //    var createPlayerViewModel = new CreatePlayerViewModel { BasketballNiId = curUserId };

        //    return View(createPlayerViewModel);
        //}

        //public async Task<IActionResult> Create(Player player)
        //{
        //    if (!ModelState.IsValid)
        //    {

        //        return View(player);
        //    }
        //    _playerService.Add(player);
        //    return RedirectToAction("Index");

        //}

        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createPlayerViewModel = new CreatePlayerViewModel { BasketballNiId = curUserId };

            return View(createPlayerViewModel);
        }

        [HttpPost]

        public async Task<IActionResult> Create(Player player)
        {
            if (!ModelState.IsValid)
            {
                return View(player);
            }
            _playerService.Add(player);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var player = await _playerService.GetByIdAsync(id);
            if (player == null) return View("Error");
            var playerVM = new EditPlayerViewModel
            {
                Name = player.Name,
                TeamName = player.TeamName,
                Points = player.Points,
                Rebounds = player.Rebounds,
                Assists = player.Assists,
                Steals = player.Steals,
                Blocks = player.Blocks
            };

            return View(playerVM);
        }
        

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditPlayerViewModel playerVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit team information");
                return View("Edit", playerVM);
            }

            var userPlayer = await _playerService.GetByIdAsyncNoTracking(id);

            var player = new Player 
            {
                Player_id = id,
                Name = playerVM.Name,
                TeamName =playerVM.TeamName,
                Points = playerVM.Points,
                Rebounds = playerVM.Rebounds,
                Assists = playerVM.Assists,
                Steals = playerVM.Steals,
                Blocks = playerVM.Blocks
            };

            _playerService.Update(player);

            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Delete(int id)
        {
            var playerDetails = await _playerService.GetByIdAsync(id);
            if (playerDetails == null) return View("Error");
            return View(playerDetails);
        }



        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePlayer(int id)
        {
            var playerDetails =  await _playerService.GetByIdAsync(id);
            //var playerDetails = _context.Players.FirstOrDefault(o => o.Player_id == id);
            if (playerDetails == null) return View("Error");

            _playerService.Delete(playerDetails);
            return RedirectToAction("Index");
        }



    }
}

Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Test2.Data;
using Test2.Interfaces;
using Test2.Models;
using Test2.ViewModels;
//using Test2.Helpers;

namespace Test2.Controllers
{
    public class TeamController : Controller
    {

        private readonly ITeamService _teamService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public TeamController(ITeamService teamService, IHttpContextAccessor httpContextAccessor)
        {
            _teamService = teamService;
            _httpContextAccessor = httpContextAccessor;


        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Team> teams = await _teamService.GetAll();
            return View(teams);

            //List<Team> teams = _context.Teams.ToList();
            //return View(teams);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Team team = await _teamService.GetByIdAsync(id);
            return View(team);
        }


        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createTeamViewModel = new CreateTeamViewModel { BasketballNiId = curUserId };
               
            return View(createTeamViewModel);
        }


        

    [HttpPost]
    public async Task<IActionResult> Create(Team team)
    {
        if (!ModelState.IsValid)
        {

            return View(team);
        }
        _teamService.Add(team);
        return RedirectToAction("Index");

    }

    public async Task<IActionResult> Edit(int id)
        {
            var team = await _teamService.GetByIdAsync(id);
            if (team == null) return View("Error");
            var teamVM = new EditTeamViewModel
            {
                Name = team.Name,
                Description = team.Description,
                LeagueName = team.LeagueName
            };
            return View(teamVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditTeamViewModel teamVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit team information");
                return View("Edit", teamVM);
            }

            var userTeam = await _teamService.GetByIdAsyncNoTracking(id);

            var team = new Team
            {
                Id = id,
                Name = teamVM.Name,
                Description = teamVM.Description,
                LeagueName = teamVM.LeagueName,
            };

            _teamService.Update(team);

            return RedirectToAction("Index");

        }


        public async Task<IActionResult> Delete (int id)
        {
            var teamDetails = await _teamService.GetByIdAsync(id);
            if (teamDetails == null) return View("Error");
            return View(teamDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteTeam(int id)
        {
            var teamDetails = await _teamService.GetByIdAsync(id);
            if (teamDetails == null) return View("Error");

            _teamService.Delete(teamDetails);
            return RedirectToAction("Index");
        }

    }
}

Views/Hub/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

@model Test2.ViewModels.HubViewModel

<h1 class="display-4 fw-normal">User Dashboard</h1>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Team" asp-action="Create">Create a new Team</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="League" asp-action="Create">Create a new League</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Player" asp-action="Create">Create a new Player</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="FixtureAndResult" asp-action="Create">Create a new Fixture or Result</a>

<div class="album py-5 bg-light">
    <div class="container">
        <h2 class="display-4 fw-normal">Your Teams</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            @foreach (var item in Model.Teams)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        @*<img class="card-img-top" src="@item.Name" width="100%" height="225" alt="Card image cap">*@
                        <img width="100%" height="225" alt="Card image cap" src="https://th.bing.com/th/id/R.f8ba61c51225d206c63cb7312dc5e4b4?rik=hwATBiueb8kReg&riu=http%3a%2f%2fwww.basketballni.com%2fwp-content%2fuploads%2f2015%2f09%2fBNI-Logo.png&ehk=ALyuN15Wg8cR8eH1b%2fwCHA6N7ugyaUcYtrrBLuMDH7E%3d&risl=&pid=ImgRaw&r=0" />

                        <div class="card-body">
                            <p class="card-text">@item.Name</p>
                            <p class="card-text">@item.Name</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Team" asp-action="Detail" asp-route-id="@item.Id"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <a asp-controller="Team" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Team" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.LeagueName</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <h2 class="display-4 fw-normal">Your Leagues</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (var item in Model.Leagues)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        @*<img class="card-img-top" src="@item.Name" width="100%" height="225" alt="Card image cap">*@
                        <img width="100%" height="225" alt="Card image cap" src="https://th.bing.com/th/id/R.f8ba61c51225d206c63cb7312dc5e4b4?rik=hwATBiueb8kReg&riu=http%3a%2f%2fwww.basketballni.com%2fwp-content%2fuploads%2f2015%2f09%2fBNI-Logo.png&ehk=ALyuN15Wg8cR8eH1b%2fwCHA6N7ugyaUcYtrrBLuMDH7E%3d&risl=&pid=ImgRaw&r=0" />
                        <div class="card-body">
                            <p class="card-text">@item.Leaguename</p>
                            <p class="card-text">@item.Leaguename</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="League" asp-action="Detail" asp-route-id="@item.League_id"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <a asp-controller="League" asp-action="Edit" asp-route-id="@item.League_id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="League" asp-action="Delete" asp-route-id="@item.League_id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.LeagueDescription</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <h2 class="display-4 fw-normal">Your Players</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (var item in Model.Players)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        @*<img class="card-img-top" src="@item.Name" width="100%" height="225" alt="Card image cap">*@
                        <img width="100%" height="225" alt="Card image cap" src="https://th.bing.com/th/id/R.f8ba61c51225d206c63cb7312dc5e4b4?rik=hwATBiueb8kReg&riu=http%3a%2f%2fwww.basketballni.com%2fwp-content%2fuploads%2f2015%2f09%2fBNI-Logo.png&ehk=ALyuN15Wg8cR8eH1b%2fwCHA6N7ugyaUcYtrrBLuMDH7E%3d&risl=&pid=ImgRaw&r=0" />
                        <div class="card-body">
                            <p class="card-text">@item.Name</p>
                            <p class="card-text">@item.Name</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Player" asp-action="Detail" asp-route-id="@item.Player_id"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <a asp-controller="Player" asp-action="Edit" asp-route-id="@item.Player_id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Player" asp-action="Delete" asp-route-id="@item.Player_id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.Name</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <h2 class="display-4 fw-normal">Your Fixtures</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (var item in Model.Fixtures)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        @*<img class="card-img-top" src="@item.Name" width="100%" height="225" alt="Card image cap">*@
                        <img width="100%" height="225" alt="Card image cap" src="https://th.bing.com/th/id/R.f8ba61c51225d206c63cb7312dc5e4b4?rik=hwATBiueb8kReg&riu=http%3a%2f%2fwww.basketballni.com%2fwp-content%2fuploads%2f2015%2f09%2fBNI-Logo.png&ehk=ALyuN15Wg8cR8eH1b%2fwCHA6N7ugyaUcYtrrBLuMDH7E%3d&risl=&pid=ImgRaw&r=0" />
                        <div class="card-body">
                            <p class="card-text">@item.DatefGame</p>
                            <p class="card-text">@item.DatefGame</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="FixtureAndResult" asp-action="Detail" asp-route-id="@item.Match_id"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <a asp-controller="FixtureAndResult" asp-action="Edit" asp-route-id="@item.Match_id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="FixtureAndResult" asp-action="Delete" asp-route-id="@item.Match_id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.Hometeam</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

    </div>
</div>